<script setup lang="ts">
import { ref } from 'vue';
import { Head, Link, useForm, router } from '@inertiajs/vue3';
import AdminLayout from '@/layouts/AdminLayout.vue';
import { Button } from '@/components/ui/button';
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from '@/components/ui/table';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Eye, Trash2, PlusCircle, CheckCircle } from 'lucide-vue-next';
import { format } from 'date-fns';
import { route } from 'ziggy-js';
import Swal from 'sweetalert2';

const props = defineProps<{
    payrolls: any;
}>();

const isGenerateModalOpen = ref(false);
const generateForm = useForm({
    month: new Date().getMonth() + 1,
    year: new Date().getFullYear(),
});

const submitGenerate = () => {
    generateForm.post(route('admin.finance.payroll.generate'), {
        onSuccess: () => {
            isGenerateModalOpen.value = false;
            Swal.fire({ icon: 'success', title: 'Generated', text: 'Payroll generated successfully', toast: true, position: 'top-end', showConfirmButton: false, timer: 3000 });
        },
        onError: () => {
             Swal.fire({ icon: 'error', title: 'Error', text: 'Failed to generate payroll', toast: true, position: 'top-end', showConfirmButton: false, timer: 3000 });
        }
    });
};

const formatCurrency = (val: any) => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN' }).format(val);

const deletePayroll = (id: string) => {
    if (confirm('Are you sure? This will delete the payroll record and all items.')) {
        router.delete(route('admin.finance.payroll.destroy', id), {
             onSuccess: () => Swal.fire({ icon: 'success', title: 'Deleted', text: 'Payroll record deleted', toast: true, position: 'top-end', showConfirmButton: false, timer: 3000 }),
        });
    }
}
</script>

<template>
    <Head title="Payroll Management" />
    <AdminLayout>
        <div class="p-6 space-y-6">
            <div class="flex items-center justify-between">
                <div>
                    <h2 class="text-3xl font-bold tracking-tight">Payroll Management</h2>
                    <p class="text-muted-foreground">Generate and manage staff payrolls.</p>
                </div>
                <Button @click="isGenerateModalOpen = true"><PlusCircle class="mr-2 h-4 w-4" /> Generate Payroll</Button>
            </div>

            <Card>
                <CardContent class="p-0">
                    <Table>
                        <TableHeader>
                            <TableRow>
                                <TableHead>Period</TableHead>
                                <TableHead>Generated By</TableHead>
                                <TableHead>Generated At</TableHead>
                                <TableHead>Total Amount</TableHead>
                                <TableHead>Status</TableHead>
                                <TableHead class="text-right">Actions</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            <TableRow v-for="payroll in payrolls.data" :key="payroll.id">
                                <TableCell class="font-medium">
                                    {{ format(new Date(payroll.year, payroll.month - 1), 'MMMM yyyy') }}
                                </TableCell>
                                <TableCell>{{ payroll.generated_by?.name }}</TableCell>
                                <TableCell>{{ format(new Date(payroll.generated_at), 'MMM d, yyyy HH:mm') }}</TableCell>
                                <TableCell class="font-bold">{{ formatCurrency(payroll.total_amount) }}</TableCell>
                                <TableCell>
                                    <Badge :variant="payroll.status === 'paid' ? 'default' : 'secondary'">{{ payroll.status }}</Badge>
                                </TableCell>
                                <TableCell class="text-right space-x-2">
                                    <Link :href="route('admin.finance.payroll.show', payroll.id)">
                                        <Button size="icon" variant="ghost"><Eye class="h-4 w-4" /></Button>
                                    </Link>
                                    <Button v-if="payroll.status !== 'paid'" size="icon" variant="ghost" class="text-destructive" @click="deletePayroll(payroll.id)"><Trash2 class="h-4 w-4" /></Button>
                                </TableCell>
                            </TableRow>
                            <TableRow v-if="payrolls.data.length === 0">
                                <TableCell colspan="6" class="text-center py-8 text-muted-foreground">No payroll records found.</TableCell>
                            </TableRow>
                        </TableBody>
                    </Table>
                </CardContent>
            </Card>

            <Dialog v-model:open="isGenerateModalOpen">
                <DialogContent>
                    <DialogHeader>
                        <DialogTitle>Generate Payroll</DialogTitle>
                        <DialogDescription>Create payroll for a specific month. Checks active staff salaries.</DialogDescription>
                    </DialogHeader>
                    <div class="grid grid-cols-2 gap-4 py-4">
                        <div class="grid gap-2">
                            <Label>Month</Label>
                            <Select v-model="generateForm.month">
                                <SelectTrigger>
                                    <SelectValue placeholder="Select Month" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem v-for="i in 12" :key="i" :value="i">{{ format(new Date(2000, i - 1), 'MMMM') }}</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>
                        <div class="grid gap-2">
                            <Label>Year</Label>
                            <Input type="number" v-model="generateForm.year" />
                        </div>
                    </div>
                    <DialogFooter>
                        <Button variant="outline" @click="isGenerateModalOpen = false">Cancel</Button>
                        <Button @click="submitGenerate" :disabled="generateForm.processing">Generate</Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        </div>
    </AdminLayout>
</template>
