<script setup lang="ts">
import { ref } from 'vue';
import { Head, Link, useForm, router } from '@inertiajs/vue3';
import AdminLayout from '@/layouts/AdminLayout.vue';
import { Button } from '@/components/ui/button';
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from '@/components/ui/table';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Eye, Trash2, PlusCircle, CheckCircle, Download, Upload } from 'lucide-vue-next';
import { format } from 'date-fns';
import { route } from 'ziggy-js';
import Swal from 'sweetalert2';

const props = defineProps<{
    payrolls: any;
}>();

const isGenerateModalOpen = ref(false);
const generateForm = useForm({
    month: new Date().getMonth() + 1,
    year: new Date().getFullYear(),
});

const isImportModalOpen = ref(false);
const selectedPayroll = ref<any>(null);
const importForm = useForm({
    file: null as File | null,
});

const openImportModal = (payroll: any) => {
    selectedPayroll.value = payroll;
    importForm.reset();
    isImportModalOpen.value = true;
};

const handleFileChange = (e: Event) => {
    const target = e.target as HTMLInputElement;
    if (target.files && target.files[0]) {
        importForm.file = target.files[0];
    }
};

const submitImport = () => {
    if (!selectedPayroll.value || !importForm.file) return;

    importForm.post(route('admin.finance.payroll.import', selectedPayroll.value.id), {
        onSuccess: () => {
            isImportModalOpen.value = false;
            importForm.reset();
            Swal.fire({
                icon: 'success',
                title: 'Imported',
                text: 'Payroll details updated successfully from uploaded file.',
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 3000,
            });
        },
        onError: () => {
            Swal.fire({
                icon: 'error',
                title: 'Import Failed',
                text: 'Failed to update payroll from file. Please check file format.',
            });
        },
    });
};

const submitGenerate = () => {
    generateForm.post(route('admin.finance.payroll.generate'), {
        onSuccess: () => {
            isGenerateModalOpen.value = false;
            Swal.fire({ icon: 'success', title: 'Generated', text: 'Payroll generated successfully', toast: true, position: 'top-end', showConfirmButton: false, timer: 3000 });
        },
        onError: () => {
             Swal.fire({ icon: 'error', title: 'Error', text: 'Failed to generate payroll', toast: true, position: 'top-end', showConfirmButton: false, timer: 3000 });
        }
    });
};

const formatCurrency = (val: any) => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN' }).format(val);

const deletePayroll = (id: string) => {
    if (confirm('Are you sure? This will delete the payroll record and all items.')) {
        router.delete(route('admin.finance.payroll.destroy', id), {
             onSuccess: () => Swal.fire({ icon: 'success', title: 'Deleted', text: 'Payroll record deleted', toast: true, position: 'top-end', showConfirmButton: false, timer: 3000 }),
        });
    }
}
</script>

<template>
    <Head title="Payroll Management" />
    <AdminLayout>
        <div class="p-6 space-y-6">
            <div class="flex items-center justify-between">
                <div>
                    <h2 class="text-3xl font-bold tracking-tight">Payroll Management</h2>
                    <p class="text-muted-foreground">Generate and manage staff payrolls.</p>
                </div>
                <Button @click="isGenerateModalOpen = true"><PlusCircle class="mr-2 h-4 w-4" /> Generate Payroll</Button>
            </div>

            <Card>
                <CardContent class="p-0">
                    <Table>
                        <TableHeader>
                            <TableRow>
                                <TableHead>Period</TableHead>
                                <TableHead>Generated By</TableHead>
                                <TableHead>Generated At</TableHead>
                                <TableHead>Total Amount</TableHead>
                                <TableHead>Status</TableHead>
                                <TableHead class="text-right">Actions</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            <TableRow v-for="payroll in payrolls.data" :key="payroll.id">
                                <TableCell class="font-medium">
                                    {{ format(new Date(payroll.year, payroll.month - 1), 'MMMM yyyy') }}
                                </TableCell>
                                <TableCell>{{ payroll.generated_by?.name }}</TableCell>
                                <TableCell>{{ format(new Date(payroll.generated_at), 'MMM d, yyyy HH:mm') }}</TableCell>
                                <TableCell class="font-bold">{{ formatCurrency(payroll.total_amount) }}</TableCell>
                                <TableCell>
                                    <Badge :variant="payroll.status === 'paid' ? 'default' : 'secondary'">{{ payroll.status }}</Badge>
                                </TableCell>
                                <TableCell class="text-right space-x-2">
                                    <Link :href="route('admin.finance.payroll.show', payroll.id)" title="View Payroll Details">
                                        <Button size="icon" variant="ghost"><Eye class="h-4 w-4" /></Button>
                                    </Link>
                                    <a :href="route('admin.finance.payroll.export', payroll.id)" target="_blank" title="Export Excel">
                                        <Button size="icon" variant="ghost" class="text-emerald-700 hover:text-emerald-800"><Download class="h-4 w-4" /></Button>
                                    </a>
                                    <Button v-if="payroll.status !== 'paid'" size="icon" variant="ghost" class="text-indigo-600 hover:text-indigo-700" title="Upload / Import Spreadsheet" @click="openImportModal(payroll)">
                                        <Upload class="h-4 w-4" />
                                    </Button>
                                    <Button v-if="payroll.status !== 'paid'" size="icon" variant="ghost" class="text-destructive" @click="deletePayroll(payroll.id)" title="Delete Payroll"><Trash2 class="h-4 w-4" /></Button>
                                </TableCell>
                            </TableRow>
                            <TableRow v-if="payrolls.data.length === 0">
                                <TableCell colspan="6" class="text-center py-8 text-muted-foreground">No payroll records found.</TableCell>
                            </TableRow>
                        </TableBody>
                    </Table>
                </CardContent>
            </Card>

            <!-- Import Payroll Modal -->
            <Dialog v-model:open="isImportModalOpen">
                <DialogContent class="max-w-md">
                    <DialogHeader>
                        <DialogTitle class="flex items-center gap-2">
                            <Upload class="h-5 w-5 text-indigo-600" /> Upload & Update Payroll
                        </DialogTitle>
                        <DialogDescription>
                            Upload an edited Excel or CSV spreadsheet to update basic salaries, allowances, deductions, status, or remarks for this payroll run.
                        </DialogDescription>
                    </DialogHeader>

                    <form @submit.prevent="submitImport" class="space-y-4 py-2">
                        <div class="space-y-2">
                            <Label for="payroll_index_file" class="font-semibold text-xs uppercase tracking-wider text-slate-600">
                                Select Payroll Spreadsheet (.xlsx, .csv, .xls)
                            </Label>
                            <Input 
                                id="payroll_index_file" 
                                type="file" 
                                accept=".csv, .xls, .xlsx" 
                                @change="handleFileChange" 
                                required 
                            />
                        </div>

                        <div v-if="importForm.errors.file" class="p-3 bg-rose-50 border border-rose-200 text-rose-700 text-xs rounded-lg font-medium">
                            {{ importForm.errors.file }}
                        </div>

                        <DialogFooter class="pt-3">
                            <Button type="button" variant="outline" @click="isImportModalOpen = false">Cancel</Button>
                            <Button type="submit" class="bg-indigo-600 hover:bg-indigo-700 font-bold" :disabled="importForm.processing">
                                <Upload class="mr-1.5 h-4 w-4" /> Upload & Update
                            </Button>
                        </DialogFooter>
                    </form>
                </DialogContent>
            </Dialog>

            <Dialog v-model:open="isGenerateModalOpen">
                <DialogContent>
                    <DialogHeader>
                        <DialogTitle>Generate Payroll</DialogTitle>
                        <DialogDescription>Create payroll for a specific month. Checks active staff salaries.</DialogDescription>
                    </DialogHeader>
                    <div class="grid grid-cols-2 gap-4 py-4">
                        <div class="grid gap-2">
                            <Label>Month</Label>
                            <Select v-model="generateForm.month">
                                <SelectTrigger>
                                    <SelectValue placeholder="Select Month" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem v-for="i in 12" :key="i" :value="i">{{ format(new Date(2000, i - 1), 'MMMM') }}</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>
                        <div class="grid gap-2">
                            <Label>Year</Label>
                            <Input type="number" v-model="generateForm.year" />
                        </div>
                    </div>
                    <DialogFooter>
                        <Button variant="outline" @click="isGenerateModalOpen = false">Cancel</Button>
                        <Button @click="submitGenerate" :disabled="generateForm.processing">Generate</Button>
                    </DialogFooter>
                </DialogContent>
            </Dialog>
        </div>
    </AdminLayout>
</template>
